CREATE TABLE ECOMMDB.SUPPLIER
(
SUPP_ID INT PRIMARY KEY,
SUPP_NAME VARCHAR(50) NOT NULL,
SUPP_CITY VARCHAR(50) NOT NULL,
SUPP_PHONE VARCHAR(50) NOT NULL
);

CREATE TABLE ECOMMDB.CUSTOMER
(
CUS_ID INT PRIMARY KEY,
CUS_NAME VARCHAR(50) NOT NULL,
CUS_CITY VARCHAR(50) NOT NULL,
CUS_PHONE VARCHAR(50) NOT NULL,
CUS_GENDER CHAR
);
CREATE TABLE ECOMMDB.CATEGORY
(
CAT_ID INT PRIMARY KEY,
CUS_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE ECOMMDB.PRODUCT
(
PRO_ID INT PRIMARY KEY,
CAT_ID INT,
PRO_NAME VARCHAR(20) NOT NULL DEFAULT 'Dummy',
PRO_DESC VARCHAR(60),
CONSTRAINT FK_CAT_ID  FOREIGN KEY(CAT_ID) REFERENCES CATEGORY(CAT_ID)
);

CREATE TABLE ECOMMDB.SUPPLIER_PRICING
(PRICING_ID INT PRIMARY KEY,
PRO_ID INT,
SUPP_ID INT,
CONSTRAINT FK_PRO_ID FOREIGN KEY(PRO_ID) REFERENCES PRODUCT(PRO_ID),
CONSTRAINT FK_SUPPLIER_ID FOREIGN KEY(SUPP_ID) REFERENCES SUPPLIER(SUPP_ID),
SUPP_PRICE INT DEFAULT 0
);


CREATE TABLE ECOMMDB.ORD
(ORD_ID INT PRIMARY KEY,
CUS_ID INT,
PRICING_ID INT,
ORD_AMT INT NOT NULL,
ORD_DATE DATE NOT NULL,
CONSTRAINT FK_CUS_ID FOREIGN KEY(CUS_ID) REFERENCES CUSTOMER(CUS_ID),
CONSTRAINT FK_PRICING_ID FOREIGN KEY(PRICING_ID) REFERENCES SUPPLIER_PRICING(PRICING_ID)
);


CREATE TABLE ECOMMDB.RATING
(

RAT_ID INT PRIMARY KEY,
RAT_RATSTARS INT NOT NULL
);

ALTER TABLE ECOMMDB.RATING
ADD ORD_ID INT;



